<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeID = $storeManager->getStore()->getStoreId();
if ($storeID == 3 || $storeID == 1) {
?>

    <div class="field customer_will_email_license">
        <input type="checkbox" name="customer_will_email_license" id="customer_will_email_license" title="" value="1" class="input-text" data-validate="{required:false}" style="top:0;">
        <label class="label" for="customer_will_email_license">
            <span>I am a professional and I will email my certification to <a href="mailto:webordersuk@nailalliance.co.uk">webordersuk@nailalliance.co.uk</a></span>
        </label>
    </div>

<?php
}
?>
<style>
    .fieldset.file-upload {
        margin: 0;
        padding-bottom: 1rem;
    }

    .fieldset.additional_info {
        margin-bottom: 0;
    }
</style>